services:
  hotels-api:
    image: iqhater/hotels_api:latest
    container_name: hotels-api
    env_file:
      - ../.env
    volumes:
      - ../hotels:/hotels
    ports:
      - "4000:4000"
    depends_on:
      - sqlite
