version: "3"

# Global environment variables
env:
  # Go parameters
  GOARCH: amd64
  GOBUILD: go build
  GOCLEAN: go clean
  GOTEST: go test
  GOTOOL: go tool
  GOGET: go get
  GOMOD: go mod
  GOINST: go install

  PLATFORM: windows.exe

  MODULE_NAME: hotels_api

  # Binary name
  BINARY_NAME: hotels_api

  # App entrypoint path
  APP_ENTRYPOINT: ./cmd/app
  API_DOCS_ENTRYPOINT: ./cmd/api-docs

  # Database parameters
  DB_DRIVER: sqlite3
  DSN: ./hotels_test_db.sql
  MIGRATIONS_PATH: ./migrations

tasks:
  # Debug for test Taskfile output
  debug:
    cmds:
      - echo "⚙️ Debug info"
      - if [ $(go env GOOS) == "windows" ]; then echo "Windows OK!"; fi

  # Install dependencies
  install:
    silent: true
    cmds:
      - echo "📦 Install Dependencies"
      - go mod tidy && go mod verify

  # Database migrations (goose)
  # Create new migrations
  create:
    silent: true
    cmds:
      - echo "💾 Create Database Migrations"
      - GOOSE_DRIVER=${DB_DRIVER} GOOSE_DBSTRING=${DSN} goose -dir=${MIGRATIONS_PATH} create add_regions_table sql
      - GOOSE_DRIVER=${DB_DRIVER} GOOSE_DBSTRING=${DSN} goose -dir=${MIGRATIONS_PATH} create add_hotels_table sql
      - GOOSE_DRIVER=${DB_DRIVER} GOOSE_DBSTRING=${DSN} goose -dir=${MIGRATIONS_PATH} create add_hotels_fts_indexed_table sql
      - GOOSE_DRIVER=${DB_DRIVER} GOOSE_DBSTRING=${DSN} goose -dir=${MIGRATIONS_PATH} create update_hotels_fts_indexed_table_tokenize sql

  # Apply all migrations
  up:
    silent: true
    cmds:
      - echo "💾 Apply Database Migrations"
      - GOOSE_DRIVER=${DB_DRIVER} GOOSE_DBSTRING=${DSN} goose -dir=${MIGRATIONS_PATH} up

  # Roll back all migrations
  reset:
    silent: true
    cmds:
      - echo "💾 Apply Database Migrations"
      - GOOSE_DRIVER=${DB_DRIVER} GOOSE_DBSTRING=${DSN} goose -dir=${MIGRATIONS_PATH} reset

  # Build app
  build:
    silent: true
    cmds:
      - $GOBUILD -o ${BINARY_NAME}_${PLATFORM} --tags "fts5" $APP_ENTRYPOINT
      - echo "📦 Build Done"

  # Build api docs
  build:docs:
    silent: true
    cmds:
      - $GOBUILD -o ${BINARY_NAME}_${PLATFORM} $API_DOCS_ENTRYPOINT
      - echo "📦 Build Done"

  # Build app for all platforms
  build-all:
    cmds:
      - for: ["darwin", "linux", "windows.exe"]
        cmd: $GOBUILD -o ${BINARY_NAME}_{{ .ITEM }} $APP_ENTRYPOINT
      - echo "📦 Builds Done"

  # Build and run
  run:
    silent: true
    deps: [build]
    cmds:
      - echo "🚀 Running App"
      - ./${BINARY_NAME}_${PLATFORM}

  # Build and run API docs server
  run:docs:
    silent: true
    deps: [build:docs]
    cmds:
      - echo "🚀 Running API Docs Server"
      - ./${BINARY_NAME}_${PLATFORM}

  # Build Docker Image
  build:docker:
    silent: true
    cmds:
      - echo "📦 Build & Tag Docker Image"
      - docker build -t hotels_api_local ./deployments/. #TODO:
      - docker tag hotels_api_local:latest hotels_api_local:staging
      - docker-compose -f ./deployments/docker-compose.yml up -d

  # Run in docker
  run:docker:
    silent: true
    deps: [build:docker]
    cmds:
      - echo "🚀 Running App in Docker"
      - docker-compose -f ./deployments/docker-compose.yml up -d

  # Clean app binaries
  clean:
    cmds:
      - echo "🧹 Clean App Binaries"
      - for: ["darwin", "linux", "windows"]
        cmd: if [ $(go env GOOS) == {{ .ITEM }} ]; then rm ${BINARY_NAME}_${PLATFORM}; fi

  # Run unit tests
  test:
    silent: true
    cmds:
      - echo "🧪 Running Unit Tests"
      - go test -v -race -cover -count=1 --tags "fts5" ./...

      # clear temp test files. comment if you want to keep them
      - rm -rf ./test/temp/**

  # Lint
  lint:
    silent: true
    cmds:
      - echo "🔦 Running Code Linter"
      - golangci-lint run
