name: Tests
on:
  push:
    branches: [develop, with-sqlite]

jobs:
  run_tests:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x, 1.26.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup environments
        env:
          HTTP_PORT: ${{ secrets.HTTP_PORT}}
          HOTELS_PATH: ${{ secrets.HOTELS_PATH }}
        run: |
          echo "HTTP_PORT=$HTTP_PORT" >> .env
          echo "HOTELS_PATH=$HOTELS_PATH" >> .env

      - name: Check go mod
        run: go mod tidy

      - name: Run tests and show coverage
        run: go test -v -race -cover -count=1 --tags "fts5" ./...
