name: Build and Push Docker image to Registry
on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run tests
      - run: go test -race -v -cover ./...

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Push to Docker Registry
        uses: docker/build-push-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
          tags: latest
          repository: iqhater/hotels_api
